version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy/next-app
    overwrite: yes
permissions:
  - object: /home/ubuntu/deploy/next-app
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root